import { Colors } from '../theme.types';

export const colors: Colors = {
  error: '#EF4444',
  success: '#84CC16',
  warning: '#F97316',
  onSurface: '#FEF7FF',
  onSurfaceVariant: '#45464F',
  inverseOnSurface: '#F2F0F4',
  inverseSurface: '#303034',
  primary: '#6750A4',
  'primary.onPrimary': '#FFFFFF',
  'primary.primaryContainer': '#EADDFF',
  'primary.onPrimaryContainer': '#21005D',
  secondary: '#595E72',
  'secondary.onSecondary': '#FFFFFF',
  'secondary.secondaryContainer': '#DDE1F9',
  'secondary.onSecondaryContainer': '#161B2C',
  outline: '#79747E',
  'outline.outlineVariant': '#C5C6D0',
  surface: '#FBF8FD',
  'surface.surfaceVariant': '#49454F',
  'surface.containerHighest': '#E4E2E6',
  'surface.containerHigh': '#E9E7EC',
  'surface.container': '#EFEDF1',
  'surface.containerLow': '#F5F3F7',
  'surface.containerLowest': '#FFFFFF',
  'surface.dim': '#DBD9DD',
  'surface.opacity': '#1D1B201F',
};
