import { Colors, MaybeNestedObject } from '../theme.types';

export const colors: Record<Colors, MaybeNestedObject | string> = {
  // error: palette.RED_500,
  // success: palette.LIME_500,
  // text: palette.NEUTRAL_1000,
  // warning: palette.ORANGE_500,
  // primary: palette.PRIMARY_500,
  // outline: palette.NEUTRAL_300,
  // secondary: palette.PRIMARY_900,
  // disabled: palette.NEUTRAL_200,
  // textAccent: palette.PRIMARY_50,
  // background: palette.NEUTRAL_50,
  // foreground: palette.NEUTRAL_700,
  // textSoft: palette.NEUTRAL_500,
  // textDisabled: palette.NEUTRAL_900,
  // textBackground: palette.NEUTRAL_0,
  // textPlaceholder: palette.NEUTRAL_300,
  // border: palette.NEUTRAL_300,
  semantic: {
    error: '#EF4444',
    success: '#84CC16',
    warning: '#F97316',
  },
  onSurface: {
    onSurface: '#1B1B1F',
    onSurfaceVariant: '#45464F',
    inverseOnSurface: '#F2F0F4',
    inverseSurface: '#303034',
  },
  primary: {
    primary: '#0053DB',
    onPrimary: '#FFFFFF',
    primaryContainer: '#DBE1FF',
    onPrimaryContainer: '#00174B',
  },
  secondary: {
    secondary: '#595E72',
    onSecondary: '#FFFFFF',
    secondaryContainer: '#DDE1F9',
    onSecondaryContainer: '#161B2C',
  },
  outline: {
    outline: '#757680',
    outlineVariant: '#C5C6D0',
  },
  surface: {
    surfaceVariant: { backgroundColor: '#E2E2EC' },
    surface: { backgroundColor: '#FBF8FD' },
    containerHighest: { backgroundColor: '#E4E2E6' },
    containerHigh: { backgroundColor: '#E9E7EC' },
    container: { backgroundColor: '#EFEDF1' },
    containerLow: { backgroundColor: '#F5F3F7' },
    containerLowest: { backgroundColor: '#FFFFFF' },
    dim: { backgroundColor: '#DBD9DD' },
  },
};
