import { Colors } from '../theme.types';

export const colors: Colors = {
  primary: '#0053DB',
  'primary.onPrimary': '#FFF',
  'primary.primaryContainer': '#DBE1FF',
  'primary.onPrimaryContainer': '#00174B',
  warning: '#D87706',
  'warning.onWarning': '#fff',
  'warning.warningContainer': '#FDF2C6',
  'warning.onWarningContainer': '#76340F',
  error: '#E53E3E',
  'error.onError': '#fff',
  'error.errorContainer': '#FEE3E3',
  'error.onErrorContainer': '#822727',
  success: '#16A24A',
  'success.onSuccess': '#fff',
  'success.successContainer': '#DBFBE6',
  'success.onSuccessContainer': '#14522D',
  surface: '#F8F9FD',
  'surface.containerLowest': '#fff',
  'surface.containerLow': '#F3F3F7',
  'surface.container': '#EDEDF1',
  'surface.containerHigh': '#E7E7EC',
  'surface.containerHighest': '#E2E2E6',
  onSurface: '#1B1B1F',
  outlile: '#76767A',
  'outline.varient': '#C6C6CA',
};
