import { Colors } from '../theme.types';

export const colors: Colors = {
  primary: '#B4C5FF',
  'primary.onPrimary': '#002A78',
  'primary.primaryContainer': '#003EA8',
  'primary.onPrimaryContainer': '#DBE1FF',
  warning: '#FCE58A',
  'warning.onWarning': '#91400E',
  'warning.warningContainer': '#B35309',
  'warning.onWarningContainer': '#FDF2C6',
  error: '#FED7D7',
  'error.onError': '#9B2C2C',
  'error.errorContainer': '#C53030',
  'error.onErrorContainer': '#FEE3E3',
  success: '#BAF6CF',
  'success.onSuccess': '#166434',
  'success.successContainer': '#157F3D',
  'success.onSuccessContainer': '#DBFBE6',
  surface: '#131316',
  'surface.containerLowest': '#0D0D11',
  'surface.containerLow': '#1B1B1F',
  'surface.container': '#1F1F23',
  'surface.containerHigh': '#292A2D',
  'surface.containerHighest': '#343438',
  onSurface: '#E2E2E6',
  outlile: '#909094',
  'outline.varient': '#46464A',
};
