import { pallete } from '../design-system/palette';
import { Theme } from '../theme.types';

export const colors: Theme['colors'] = {
  primary: pallete.PRIMARY_80,
  onPrimary: pallete.PRIMARY_20,
  primaryContainer: pallete.PRIMARY_30,
  onPrimaryContainer: pallete.PRIMARY_90,
  warning: pallete.WARNING_80,
  onWarning: pallete.WARNING_20,
  warningContainer: pallete.WARNING_30,
  onWarningContainer: pallete.WARNING_90,
  error: pallete.ERROR_80,
  onError: pallete.ERROR_20,
  errorContainer: pallete.ERROR_30,
  onErrorContainer: pallete.ERROR_90,
  success: pallete.SUCCESS_80,
  onSuccess: pallete.SUCCESS_20,
  successContainer: pallete.SUCCESS_30,
  onSuccessContainer: pallete.SUCCESS_90,
  surface: pallete.NEUTRAL_6,
  lowestContainer: pallete.NEUTRAL_4,
  lowContainer: pallete.NEUTRAL_10,
  container: pallete.NEUTRAL_12,
  highContainer: pallete.NEUTRAL_17,
  highestContainer: pallete.NEUTRAL_22,
  onSurface: pallete.NEUTRAL_90,
  outlile: pallete.NEUTRAL_60,
  varientOutline: pallete.NEUTRAL_30,
};
