import { pallete } from '../design-system/palette';
import { Theme } from '../theme.types';

export const colors: Theme['colors'] = {
  primary: pallete.PRIMARY_80,
  'primary.onPrimary': pallete.PRIMARY_20,
  'primary.primaryContainer': pallete.PRIMARY_30,
  'primary.onPrimaryContainer': pallete.PRIMARY_90,
  warning: pallete.WARNING_80,
  'warning.onWarning': pallete.WARNING_20,
  'warning.warningContainer': pallete.WARNING_30,
  'warning.onWarningContainer': pallete.WARNING_90,
  error: pallete.ERROR_80,
  'error.onError': pallete.ERROR_20,
  'error.errorContainer': pallete.ERROR_30,
  'error.onErrorContainer': pallete.ERROR_90,
  success: pallete.SUCCESS_80,
  'success.onSuccess': pallete.SUCCESS_20,
  'success.successContainer': pallete.SUCCESS_30,
  'success.onSuccessContainer': pallete.SUCCESS_90,
  surface: pallete.NEUTRAL_6,
  'surface.containerLowest': pallete.NEUTRAL_4,
  'surface.containerLow': pallete.NEUTRAL_10,
  'surface.container': pallete.NEUTRAL_12,
  'surface.containerHigh': pallete.NEUTRAL_17,
  'surface.containerHighest': pallete.NEUTRAL_22,
  onSurface: pallete.NEUTRAL_90,
  outlile: pallete.NEUTRAL_60,
  'outline.varient': pallete.NEUTRAL_30,
};
